### ISSUE TITLE
README.md file

### ISSUE THREAD

**Issue by huan-ds** [UBC-MDS/Abalone_Age_Prediction#7]
Hi, I've been complete the most part of README.md file. Here are two issues I need some help with:

- 1. License: How to check the license for a public dataset on uci website.
- 2. Dependencies：How to check the minimal dependencies for this project?

**Comment by charlessuresh** [comment]
- License: I think it's recommended to use the [MIT license](https://choosealicense.com/licenses/mit/)
- Dependencies: My guess is that we have to create a new environment, test this project in the new test env and then use the terminal to list the dependencies as demonstrated in 521 Lecture 8. I maybe wrong

**Comment by huan-ds** [comment]
Problem solved in milestone 1.
